# Generated by Django 4.2.7 on 2023-12-18 18:59

import consult.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('suit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appnt_type', models.CharField(choices=[('CALLBACK', 'CALLBACK'), ('MEASUREMENT', 'MEASUREMENT'), ('CONSULTATION', 'CONSULTATION'), ('DRAFT', 'DRAFT')], default='DRAFT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('identifier', models.CharField(default=consult.models.generate_short_uuid, editable=False, error_messages={'unique': 'Appointment with this identifier already exists.'}, max_length=100, unique=True)),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.customer')),
                ('suit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suit.suitbuild')),
            ],
        ),
    ]
