# Generated by Django 4.2.7 on 2023-11-19 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0002_appointment_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
