# Generated by Django 4.2.7 on 2023-11-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0004_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='customer_address',
        ),
    ]
