# Generated by Django 4.2.7 on 2023-11-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0005_remove_appointment_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
