# Generated by Django 4.2.7 on 2023-12-05 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0006_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='customer',
        ),
    ]
