# Generated by Django 4.2.7 on 2023-12-05 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suit', '0001_initial'),
        ('consult', '0008_appointment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='suit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suit.suitbuild'),
        ),
    ]
