# Generated by Django 4.2.7 on 2023-12-05 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceNDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('composition', models.CharField(blank=True, max_length=100, null=True)),
                ('season', models.CharField(blank=True, max_length=100, null=True)),
                ('fitness', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='suitbuild',
            name='monogram_text',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('pricendescriptions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suit.pricendescriptions')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('picture', models.ImageField(upload_to='images/suit/')),
            ],
            bases=('suit.pricendescriptions',),
        ),
    ]
