# Generated by Django 4.2.7 on 2023-12-30 11:57

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('suit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('composition', models.CharField(blank=True, max_length=100, null=True)),
                ('season', models.CharField(blank=True, max_length=100, null=True)),
                ('fineness', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='suitbuild',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='suitbuild',
            name='monogram_text',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='WaistcoatPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(upload_to='images/suit/', validators=[utils.validators.only_svg_png_images])),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suit.partdetail')),
                ('pictures', models.ManyToManyField(blank=True, related_name='wcoat_patt_pics', to='home.pictures')),
            ],
        ),
        migrations.CreateModel(
            name='WaistcoatLapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(upload_to='images/suit/', validators=[utils.validators.only_svg_png_images])),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suit.partdetail')),
                ('pictures', models.ManyToManyField(blank=True, related_name='wcoat_lapel_pics', to='home.pictures')),
            ],
        ),
        migrations.CreateModel(
            name='ShirtColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suit.partdetail')),
                ('pictures', models.ManyToManyField(blank=True, related_name='shirt_pics', to='home.pictures')),
            ],
        ),
        migrations.CreateModel(
            name='PantStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(upload_to='images/suit/', validators=[utils.validators.only_svg_png_images])),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suit.partdetail')),
                ('pictures', models.ManyToManyField(blank=True, related_name='pant_pics', to='home.pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/suit/')),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suit.partdetail')),
                ('pictures', models.ManyToManyField(blank=True, related_name='fabric_pics', to='home.pictures')),
            ],
        ),
        migrations.CreateModel(
            name='BlazerPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(upload_to='images/suit/', validators=[utils.validators.only_svg_png_images])),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suit.partdetail')),
                ('pictures', models.ManyToManyField(blank=True, related_name='blazer_pics', to='home.pictures')),
            ],
        ),
    ]
