# Generated by Django 4.2.7 on 2023-12-05 21:22

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('suit', '0002_pricendescriptions_suitbuild_monogram_text_fabric'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlazerPattern',
            fields=[
                ('pricendescriptions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suit.pricendescriptions')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(upload_to='images/city/', validators=[utils.validators.only_svg_png_images])),
                ('picture', models.ImageField(upload_to='images/suit/')),
            ],
            bases=('suit.pricendescriptions',),
        ),
    ]
