# Generated by Django 4.2.7 on 2023-12-10 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suit', '0003_blazerpattern_is_active_fabric_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blazerpattern',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fabric',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suit.suitpartdetail'),
        ),
        migrations.AddField(
            model_name='shirtcolor',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suit.suitpartdetail'),
        ),
        migrations.AlterField(
            model_name='blazerpattern',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suit.suitpartdetail'),
        ),
    ]
