# Generated by Django 4.2.7 on 2023-12-05 21:24

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('suit', '0003_blazerpattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='PantStyle',
            fields=[
                ('blazerpattern_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suit.blazerpattern')),
            ],
            bases=('suit.blazerpattern',),
        ),
        migrations.CreateModel(
            name='ShirtColor',
            fields=[
                ('pricendescriptions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suit.pricendescriptions')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(upload_to='images/city/', validators=[utils.validators.only_svg_png_images])),
            ],
            bases=('suit.pricendescriptions',),
        ),
        migrations.CreateModel(
            name='WaistcoatLapel',
            fields=[
                ('blazerpattern_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suit.blazerpattern')),
            ],
            bases=('suit.blazerpattern',),
        ),
        migrations.CreateModel(
            name='WaistcoatPattern',
            fields=[
                ('blazerpattern_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suit.blazerpattern')),
            ],
            bases=('suit.blazerpattern',),
        ),
    ]
