# Generated by Django 4.2.7 on 2023-12-05 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suit', '0004_pantstyle_shirtcolor_waistcoatlapel_waistcoatpattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitbuild',
            name='blazer_pattern',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blazer_suit', to='suit.blazerpattern'),
        ),
        migrations.AddField(
            model_name='suitbuild',
            name='fabric',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabric_suit', to='suit.fabric'),
        ),
        migrations.AddField(
            model_name='suitbuild',
            name='pant_style',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pant_style_suit', to='suit.pantstyle'),
        ),
        migrations.AddField(
            model_name='suitbuild',
            name='shirt_color',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shirt_color_suit', to='suit.shirtcolor'),
        ),
        migrations.AddField(
            model_name='suitbuild',
            name='waistcoat_lapel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waistcoat_lapel_suit', to='suit.waistcoatlapel'),
        ),
        migrations.AddField(
            model_name='suitbuild',
            name='waistcoat_pattern',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waistcoat_pattern_suit', to='suit.waistcoatpattern'),
        ),
    ]
