# Generated by Django 4.2.7 on 2023-12-10 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suit', '0005_remove_suitbuild_blazer_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitbuild',
            name='blazer_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blazer_suit', to='suit.blazerpattern'),
        ),
        migrations.AddField(
            model_name='suitbuild',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabric_suit', to='suit.fabric'),
        ),
        migrations.AddField(
            model_name='suitbuild',
            name='pant_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pant_style_suit', to='suit.pantstyle'),
        ),
        migrations.AddField(
            model_name='suitbuild',
            name='shirt_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shirt_color_suit', to='suit.shirtcolor'),
        ),
        migrations.AddField(
            model_name='suitbuild',
            name='waistcoat_lapel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waistcoat_lapel_suit', to='suit.waistcoatlapel'),
        ),
        migrations.AddField(
            model_name='suitbuild',
            name='waistcoat_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waistcoat_pattern_suit', to='suit.waistcoatpattern'),
        ),
    ]
