# Generated by Django 4.2.7 on 2023-11-19 17:48

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.FileField(upload_to='media/images/city/', validators=[utils.validators.only_svg_png_images])),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AddressDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.TextField(blank=True, default='TBA', null=True)),
                ('landmark', models.CharField(blank=True, default='TBA', max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, default='TBA', max_length=50, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='home.city')),
            ],
        ),
    ]
