# Generated by Django 4.2.7 on 2023-12-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_testimonials_delete_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
