# Generated by Django 4.2.7 on 2023-11-30 19:43

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressdetail',
            name='customer',
        ),
        migrations.AlterField(
            model_name='city',
            name='icon',
            field=models.FileField(upload_to='images/city/', validators=[utils.validators.only_svg_png_images]),
        ),
    ]
