# Generated by Django 4.2.7 on 2023-11-30 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('home', '0003_remove_addressdetail_customer_alter_city_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressdetail',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='user.customer'),
        ),
    ]
