# Generated by Django 4.2.7 on 2023-11-30 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_addressdetail_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressdetail',
            name='city',
        ),
    ]
