# Generated by Django 4.2.7 on 2023-11-30 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_addressdetail_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressdetail',
            name='city',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='home.city'),
        ),
    ]
