# Generated by Django 4.2.7 on 2023-11-30 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_city_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressdetail',
            name='city',
        ),
    ]
