# Generated by Django 4.2.7 on 2023-12-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
